KHDI-24: Controller/Models aangemaakt voor StudyRoute/StudyRouteItem
ditmarvisser-windesheim/keuzewijzer-hbo-deeltijd-ict pull request #3
Opened 2023-05-01 15:31 UTC by BoVerzaal

Volgens mij hoort het zo met de relaties enzo

2023-05-01 15:33 UTC, BoVerzaal commented
[191d73b](https://github.com/ditmarvisser-windesheim/keuzewijzer-hbo-deeltijd-ict/pull/3/commits/191d73b9f8143782ff7a486cfeb4927fc967794d) deze hoorde er niet in! Ik haal hem gelijk weg

2023-05-01 18:04 UTC, svenk2002 requested changes
Deze controllers zijn gemaakt voor een MVC project en niet voor een API project dit klopt niet. Je stuurt vieuws terug maar hebt ook routes gemaakt die niet van toepassing zijn.

2023-05-09 18:32 UTC, kasperdeboerdev commented
We moeten even kijken naar de studyroute api denk ik, want op deze manier heb je geen idee welke modules zijn gekozen en kunnen we dit niet weergeven

2023-05-09 18:33 UTC, kasperdeboerdev requested changes
We moeten even kijken naar de studyroute api denk ik, want op deze manier heb je geen idee welke modules zijn gekozen en kunnen we dit niet weergeven

2023-05-10 11:41 UTC, svenk2002 approved these changes

2023-05-10 11:43 UTC, ditmarvisser-windesheim approved these changes

2023-05-10 11:45 UTC, merged